name: yoursportz
description: "A new Flutter project."
publish_to: "none"
version: 1.1.4
environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  video_player: ^2.8.3
  lottie: 3.1.2
  aad_oauth: ^1.0.1
  flutter_reaction_button: ^3.0.0+3
  shared_preferences: ^2.2.2
  animated_splash_screen: ^1.3.0
  http: ^1.2.1
  intl: ^0.19.0 # Updated constraint to resolve conflict
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  flutter_animation_progress_bar: ^2.3.1
  otpless_flutter: ^2.1.3
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  socket_io_client: ^2.0.3+1
  geolocator: ^12.0.0
  font_awesome_flutter: 10.7.0
  url_launcher: ^6.3.0
  camera: ^0.11.0+1
  flutter_ffmpeg: ^0.4.2
  easy_localization: ^3.0.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  dio: ^5.5.0+1
  web_socket_channel: ^3.0.1
  injectable: ^2.4.4
  flutter_dotenv: ^5.1.0
  auto_route: ^8.1.3
  app_links: ^6.2.0
  streaming_shared_preferences: ^2.0.0
  get_it: ^7.7.0
  logger: ^2.4.0
  fluttertoast: ^8.2.8
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  import_sorter: ^4.6.0
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/
    - assets/images/
    - assets/languages/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: sf-pro-display
      fonts:
        - asset: assets/fonts/sf-pro-display/sf_pro_display_regular.otf
